const books={devil:{title:'معركة الشيطان وجنوده مع الإنسان',digitalPrice:25,printPrice:25},soul:{title:'معركة السيادة بين فطرة الروح والجسد',digitalPrice:25,printPrice:25}};
const qtyPrice=(base,qty)=>qty>=2?15:base;
const bundlePrice=30;
let selectedBook=null,selectedEdition=null,selectedBundle=false;
let cart=JSON.parse(localStorage.getItem('author-books-cart')||'[]');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const previewModal=$('#previewModal'),productModal=$('#productModal'),cartEl=$('#cart'),backdrop=$('#backdrop'),checkoutModal=$('#checkoutModal');
function openModal(el){el.classList.add('open');el.setAttribute('aria-hidden','false');backdrop.classList.add('show')}
function closeAll(){[previewModal,productModal,checkoutModal].forEach(x=>{if(x){x.classList.remove('open');x.setAttribute('aria-hidden','true')}});cartEl.classList.remove('open');backdrop.classList.remove('show')}
function saveCart(){localStorage.setItem('author-books-cart',JSON.stringify(cart))}
function priceFor(item){return item.edition==='digital'?books[item.id].digitalPrice:books[item.id].printPrice}
function linePrice(item){return qtyPrice(priceFor(item),item.qty||1)*(item.qty||1)}
function cartSubtotal(){return cart.reduce((s,x)=>s+linePrice(x),0)}
function applyBundleDiscount(subtotal){const hasD=cart.some(x=>x.id==='devil'),hasS=cart.some(x=>x.id==='soul');if(hasD&&hasS&&cart.length===2){const digital=cart.filter(x=>x.edition==='digital').length,print=cart.filter(x=>x.edition==='print').length;if(digital===2||print===2)return bundlePrice}return subtotal}
$$('[data-close]').forEach(b=>b.addEventListener('click',closeAll));backdrop.addEventListener('click',closeAll);
$$('.preview-btn').forEach(btn=>btn.addEventListener('click',e=>{selectedBook=e.currentTarget.closest('.book-card').dataset.id;selectedBundle=false;$('#previewTitle').textContent=books[selectedBook].title;openModal(previewModal)}));
$$('.buy-btn').forEach(btn=>btn.addEventListener('click',e=>{selectedBook=e.currentTarget.closest('.book-card').dataset.id;selectedBundle=false;selectedEdition=null;$$('.edition').forEach(x=>x.classList.remove('selected'));$('#productTitle').textContent=books[selectedBook].title;openModal(productModal)}));
$('#bundleBtn')?.addEventListener('click',()=>{selectedBundle=true;selectedBook=null;selectedEdition=null;$$('.edition').forEach(x=>x.classList.remove('selected'));$('#productTitle').textContent='عرض الكتابين — الإصداران معًا';openModal(productModal)});
$('#previewBuy').addEventListener('click',()=>{previewModal.classList.remove('open');$('#productTitle').textContent=books[selectedBook].title;selectedBundle=false;openModal(productModal)});
$$('.edition').forEach(btn=>btn.addEventListener('click',()=>{selectedEdition=btn.dataset.edition;$$('.edition').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')}));
$('#addToCart').addEventListener('click',()=>{if(!selectedEdition){alert('اختَر النسخة أولًا ❤️');return}if(selectedBundle){for(const id of Object.keys(books)){if(!cart.some(x=>x.id===id&&x.edition===selectedEdition))cart.push({id,edition:selectedEdition,qty:1,bundle:true})}}else{const existing=cart.find(x=>x.id===selectedBook&&x.edition===selectedEdition);if(existing)existing.qty=(existing.qty||1)+1;else cart.push({id:selectedBook,edition:selectedEdition,qty:1})}saveCart();renderCart();closeAll();cartEl.classList.add('open');backdrop.classList.add('show')});
$('#cartBtn').addEventListener('click',()=>{cartEl.classList.add('open');backdrop.classList.add('show')});$('#cartClose').addEventListener('click',closeAll);
function renderCart(){const wrap=$('#cartItems'),count=cart.reduce((n,x)=>n+(x.qty||1),0);$('#cartCount').textContent=count;if(!cart.length){wrap.innerHTML='<div class="empty">السلة فارغة حاليًا.</div>';$('#cartTotal').textContent='—';return}wrap.innerHTML=cart.map((x,i)=>{const qty=x.qty||1,unit=qtyPrice(priceFor(x),qty),old=priceFor(x);return `<div class="cart-item"><span><b>${books[x.id].title}</b><br><small>${x.edition==='digital'?'📱 إلكترونية':'📦 ورقية'} · الكمية ${qty} · <s>$${old}</s> <strong>$${unit}</strong> للنسخة</small></span><div><button class="qty" data-minus="${i}">−</button><button class="qty" data-plus="${i}">+</button><button data-remove="${i}" class="close" style="position:static;font-size:18px">×</button></div></div>`}).join('');const subtotal=cartSubtotal(),total=applyBundleDiscount(subtotal);$('#cartTotal').textContent=`$${total.toFixed(2)}`;$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart();renderCart()});$$('[data-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qty=(cart[+b.dataset.plus].qty||1)+1;saveCart();renderCart()});$$('[data-minus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.minus;cart[i].qty=(cart[i].qty||1)-1;if(cart[i].qty<=0)cart.splice(i,1);saveCart();renderCart()})}
$('#checkout').addEventListener('click',()=>{if(!cart.length){alert('السلة فارغة ❤️');return}const total=applyBundleDiscount(cartSubtotal());$('#checkoutSummary').innerHTML=cart.map(x=>{const qty=x.qty||1,unit=qtyPrice(priceFor(x),qty);return `<div><span>${books[x.id].title} — ${x.edition==='digital'?'إلكتروني':'ورقي'} × ${qty}</span><b>$${(unit*qty).toFixed(2)}</b></div>`}).join('')+`<div class="promo-line"><span>الإجمالي بعد العروض</span><b>$${total.toFixed(2)}</b></div>`;$('#shippingFields').hidden=!cart.some(x=>x.edition==='print');$('#checkoutForm').hidden=false;$('#checkoutMessage').hidden=true;openModal(checkoutModal)});
$('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),total=applyBundleDiscount(cartSubtotal()),order={name:data.get('name'),email:data.get('email'),country:data.get('country'),address:data.get('address'),items:cart,total,createdAt:new Date().toISOString()};localStorage.setItem('author-books-last-order',JSON.stringify(order));$('#checkoutMessage').textContent='تم تجهيز الطلب تجريبيًا. الدفع الحقيقي عبر Stripe سيُفعّل في المرحلة التالية مع الحفاظ على نفس الأسعار والعروض.';$('#checkoutForm').hidden=true;$('#checkoutMessage').hidden=false});
renderCart();
