const AUTHOR='عبد الرحمان راشد الرفيعي';
const books={devil:{title:'معركة الشيطان وجنوده مع الإنسان',digitalPrice:25,printPrice:25},soul:{title:'معركة السيادة بين فطرة الروح والجسد',digitalPrice:25,printPrice:25}};
const qtyPrice=(base,qty)=>qty>=2?15:base;
const bundlePrice=30;
let selectedBook=null,selectedEdition=null,selectedBundle=false;
let cart=JSON.parse(localStorage.getItem('author-books-cart')||'[]');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const previewModal=$('#previewModal'),productModal=$('#productModal'),cartEl=$('#cart'),backdrop=$('#backdrop'),checkoutModal=$('#checkoutModal');
function openModal(el){el.classList.add('open');el.setAttribute('aria-hidden','false');backdrop.classList.add('show')}
function closeAll(){[previewModal,productModal,checkoutModal].forEach(x=>{if(x){x.classList.remove('open');x.setAttribute('aria-hidden','true')}});cartEl.classList.remove('open');backdrop.classList.remove('show')}
function saveCart(){localStorage.setItem('author-books-cart',JSON.stringify(cart))}
function priceFor(item){return item.edition==='digital'?books[item.id].digitalPrice:books[item.id].printPrice}
function linePrice(item){return qtyPrice(priceFor(item),item.qty||1)*(item.qty||1)}
function cartSubtotal(){return cart.reduce((s,x)=>s+linePrice(x),0)}
function applyBundleDiscount(subtotal){const d=cart.find(x=>x.id==='devil'),s=cart.find(x=>x.id==='soul');if(!d||!s)return subtotal;return d.edition===s.edition&&d.qty===1&&s.qty===1?bundlePrice:subtotal}
function loadStyle(id,href){if(document.getElementById(id))return;const link=document.createElement('link');link.id=id;link.rel='stylesheet';link.href=href;document.head.appendChild(link)}
function loadScript(src){if(document.querySelector(`script[src="${src}"]`))return;const script=document.createElement('script');script.src=src;document.body.appendChild(script)}
function setupPreviewAssets(){loadStyle('preview-reader-style','/preview-reader.css');loadStyle('book-pages-style','/book-pages.css');loadStyle('checkout-style','/checkout.css');loadScript('/preview-reader.js');}
function refreshAuthorIdentity(){document.title=`${AUTHOR} | المكتبة الرسمية`;const brand=document.querySelector('.brand b');if(brand)brand.textContent=`دار ${AUTHOR}`;const author=document.querySelector('#author');if(author){const h=author.querySelector('h2');if(h)h.innerHTML=`${AUTHOR}<br><em>يكتب من سؤال الإنسان.</em>`;const ps=author.querySelectorAll('p');if(ps[0])ps[0].textContent=`${AUTHOR} مؤلف هذه الإصدارات، ويقدّم في كتبه مساحة للتأمل في الإنسان وما يجري داخله؛ في الروح والجسد، في الاختيار والمواجهة، وفي الأسئلة التي قد نمرّ بها دون أن نتوقف طويلًا عندها.`;if(!author.querySelector('.author-signature')){const sign=document.createElement('div');sign.className='author-signature';sign.innerHTML=`${AUTHOR} <span>· مؤلف هذه الإصدارات</span>`;author.querySelector('div:last-child')?.appendChild(sign)}}const rights=document.querySelector('#rights p:not(.eyebrow)');if(rights)rights.innerHTML=`جميع حقوق التأليف والنشر والنسخ والتوزيع محفوظة للمؤلف <strong>${AUTHOR}</strong>. شراء النسخة الإلكترونية يمنح المشتري حق الاستخدام الشخصي فقط، ولا يمنحه حق إعادة النشر أو المشاركة أو البيع أو التوزيع.`}
function injectReviewStyles(){if(document.querySelector('#reviews-style'))return;const link=document.createElement('link');link.id='reviews-style';link.rel='stylesheet';link.href='/reviews.css';document.head.appendChild(link)}
function injectReviews(){injectReviewStyles();if(document.querySelector('#reviews'))return;const section=document.createElement('section');section.id='reviews';section.className='reviews';section.innerHTML=`<div class="section-head"><div><p class="eyebrow">آراء القرّاء</p><h2>تجربة القارئ أولًا</h2></div><p>التقييمات الحقيقية تُنشر بعد إتمام الشراء والمراجعة.</p></div><div class="review-grid" id="reviewList"></div><div class="review-cta"><div><p class="eyebrow">اشتريت كتابًا؟</p><h3>خلِّ رأيك جزءًا من الحكاية.</h3><p>بعد إتمام الطلب يمكنك إرسال تقييمك وتعليقك. التقييم يبقى قيد المراجعة إلى أن نربط نظام الحسابات وقاعدة البيانات.</p></div><button class="btn dark" id="reviewBtn">اكتب تقييمًا</button></div>`;document.querySelector('#books')?.after(section);renderReviews();document.querySelector('#reviewBtn')?.addEventListener('click',()=>{if(!localStorage.getItem('author-books-last-order')){alert('التقييم متاح بعد إتمام طلب ❤️');return}const name=prompt('اسمك الظاهر؟');if(!name)return;const text=prompt('اكتب رأيك بالكتاب؟');if(!text)return;const rating=Math.max(1,Math.min(5,Number(prompt('التقييم من 1 إلى 5؟','5'))||5));const reviews=JSON.parse(localStorage.getItem('author-books-reviews')||'[]');reviews.unshift({name,text,rating,date:new Date().toISOString(),status:'pending'});localStorage.setItem('author-books-reviews',JSON.stringify(reviews));alert('وصل تقييمك للمراجعة. لن يظهر للزوار حتى يتم اعتماده. ❤️')})}
function renderReviews(){const list=$('#reviewList');if(!list)return;const reviews=JSON.parse(localStorage.getItem('author-books-reviews')||'[]');const editorial=[{name:'رأي تحريري',text:'هوية الكتب تحمل نبرة فكرية هادئة، وتضع الإنسان وأسئلته الداخلية في قلب التجربة.',rating:5,editorial:true},{name:'رأي تحريري',text:'المشروع الكتابي للرفيعي يبدأ من فكرة جميلة: أن يخرج القارئ من الصفحة وهو يحمل سؤالًا جديدًا.',rating:5,editorial:true},{name:'رأي تحريري',text:'إصدارات ذات طابع تأملي واضح، والموقع صُمم ليعطي الكتاب مساحة تليق به.',rating:5,editorial:true}];const approved=reviews.filter(r=>r.status==='approved');list.innerHTML=[...approved,...editorial].map(r=>`<article class="review-card"><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div><p>“${String(r.text).replace(/[<>]/g,'')}”</p><strong>${String(r.name).replace(/[<>]/g,'')}</strong>${r.editorial?'<small>رأي تحريري · ليس تقييمًا من عميل</small>':'<small>تقييم موثّق بعد الشراء</small>'}</article>`).join('')}
function showProduct(){selectedEdition=null;$$('.edition').forEach(x=>x.classList.remove('selected'));$('#productTitle').textContent=selectedBundle?'عرض الكتابين — الإصداران معًا':books[selectedBook].title;openModal(productModal)}
setupPreviewAssets();refreshAuthorIdentity();injectReviews();
$$('[data-close]').forEach(b=>b.addEventListener('click',closeAll));backdrop.addEventListener('click',closeAll);
$$('.preview-btn').forEach(btn=>btn.addEventListener('click',e=>{selectedBook=e.currentTarget.closest('.book-card').dataset.id;selectedBundle=false;$('#previewTitle').textContent=books[selectedBook].title;openModal(previewModal)}));
$$('.buy-btn').forEach(btn=>btn.addEventListener('click',e=>{selectedBook=e.currentTarget.closest('.book-card').dataset.id;selectedBundle=false;showProduct()}));
$('#bundleBtn')?.addEventListener('click',()=>{selectedBundle=true;selectedBook=null;showProduct()});
$('#previewBuy').addEventListener('click',()=>{previewModal.classList.remove('open');selectedBundle=false;showProduct()});
$$('.edition').forEach(btn=>btn.addEventListener('click',()=>{selectedEdition=btn.dataset.edition;$$('.edition').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected')}));
$('#addToCart').addEventListener('click',()=>{if(!selectedEdition){alert('اختَر النسخة أولًا ❤️');return}if(selectedBundle){for(const id of Object.keys(books)){const existing=cart.find(x=>x.id===id&&x.edition===selectedEdition);if(existing)existing.qty=(existing.qty||1)+1;else cart.push({id,edition:selectedEdition,qty:1,bundle:true})}}else{const existing=cart.find(x=>x.id===selectedBook&&x.edition===selectedEdition);if(existing)existing.qty=(existing.qty||1)+1;else cart.push({id:selectedBook,edition:selectedEdition,qty:1})}saveCart();renderCart();closeAll();cartEl.classList.add('open');backdrop.classList.add('show')});
$('#cartBtn').addEventListener('click',()=>{cartEl.classList.add('open');backdrop.classList.add('show')});$('#cartClose').addEventListener('click',closeAll);
function renderCart(){const wrap=$('#cartItems'),count=cart.reduce((n,x)=>n+(x.qty||1),0);$('#cartCount').textContent=count;if(!cart.length){wrap.innerHTML='<div class="empty">السلة فارغة حاليًا.</div>';$('#cartTotal').textContent='—';return}wrap.innerHTML=cart.map((x,i)=>{const qty=x.qty||1,unit=qtyPrice(priceFor(x),qty),old=priceFor(x);return `<div class="cart-item"><span><b>${books[x.id].title}</b><br><small>${x.edition==='digital'?'📱 إلكترونية':'📦 ورقية'} · الكمية ${qty} · <s>$${old}</s> <strong>$${unit}</strong> للنسخة</small></span><div><button class="qty" aria-label="نقص الكمية" data-minus="${i}">−</button><button class="qty" aria-label="زد الكمية" data-plus="${i}">+</button><button data-remove="${i}" aria-label="حذف" class="close" style="position:static;font-size:18px">×</button></div></div>`}).join('');const subtotal=cartSubtotal(),total=applyBundleDiscount(subtotal);$('#cartTotal').textContent=`$${total.toFixed(2)}`;$$('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.remove,1);saveCart();renderCart()});$$('[data-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qty=(cart[+b.dataset.plus].qty||1)+1;saveCart();renderCart()});$$('[data-minus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.minus;cart[i].qty=(cart[i].qty||1)-1;if(cart[i].qty<=0)cart.splice(i,1);saveCart();renderCart()})}
$('#checkout').addEventListener('click',()=>{if(!cart.length){alert('السلة فارغة ❤️');return}const subtotal=cartSubtotal(),total=applyBundleDiscount(subtotal),discount=Math.max(0,subtotal-total);$('#checkoutSummary').innerHTML=cart.map(x=>{const qty=x.qty||1,unit=qtyPrice(priceFor(x),qty);return `<div><span>${books[x.id].title} — ${x.edition==='digital'?'إلكتروني':'ورقي'} × ${qty}</span><b>$${(unit*qty).toFixed(2)}</b></div>`}).join('')+(discount?`<div class="promo-line"><span>خصم العرض</span><b>−$${discount.toFixed(2)}</b></div>`:'')+`<div class="promo-line"><span>الإجمالي قبل الشحن</span><b>$${total.toFixed(2)}</b></div>`;$('#shippingFields').hidden=!cart.some(x=>x.edition==='print');$('#checkoutForm').hidden=false;$('#checkoutMessage').hidden=true;openModal(checkoutModal)});
$('#checkoutForm').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget),total=applyBundleDiscount(cartSubtotal()),order={id:'BOOK-'+Date.now().toString(36).toUpperCase(),author:AUTHOR,name:data.get('name'),email:data.get('email'),country:data.get('country'),address:data.get('address'),items:cart,total,createdAt:new Date().toISOString(),paymentStatus:'pending'};localStorage.setItem('author-books-last-order',JSON.stringify(order));$('#checkoutMessage').innerHTML=`<strong>تم تجهيز طلبك المبدئي ✓</strong><br>رقم الطلب: <b>${order.id}</b><br><small>الدفع الحقيقي لم يُنفّذ بعد. سيتم تحويل هذه الخطوة إلى Stripe عند تفعيل بوابة الدفع.</small>`;$('#checkoutForm').hidden=true;$('#checkoutMessage').hidden=false;cart=[];saveCart();renderCart();setTimeout(()=>renderReviews(),0)});
renderCart();
