(() => {
  const pages={devil:[{title:'نبذة عن المؤلف',text:'عبد الرحمن راشد الرفيعي، كاتب ومفكر يتبنى منهجاً إصلاحياً أصيلاً يقوم على التدبر الحر للقرآن الكريم. يرفض الاعتماد على النقولات البشرية أو التبعية التقليدية، مؤسساً مشروعه الفكري على تفسير الآيات بالآيات استجابة للبيان الإلهي وبلغة عربية مبينة. ينطلق من قوله تعالى: {فَإِذَا قَرَأْنَاهُ فَاتَّبِعْ قُرْآنَهُ * ثُمَّ إِنَّ عَلَيْنَا بَيَانَهُ}، ليجعل القرآن مرجعه الأوحد في تقويم النفس البشرية وإعادة الإنسان إلى فطرته الصافية.'},{title:'الباب الأول: مذكرات كشف العدو',text:'رحلة الشيطان في محاصرة الإنسان\n\nأولاً: القرين — بوابته الأولى\n\nيبدأ الشيطان ملازمة الإنسان من خلال القرين. مهمته الهمس المستمر في الصدر، ومحاولة تحويل الفكر عن ذكر الله. فإن وجد قلباً متصلاً بالله، هرب منه؛ فالذكر هو جدار الصد الأول.\n\nالدليل: قال تعالى: {وَمَن يَعْشُ عَن ذِكْرِ الرَّحْمَنِ نُقَيِّضْ لَهُ شَيْطَانًا فَهُوَ لَهُ قَرِينٌ} [سورة الزخرف: 36].\n\nثانياً: جند الإنس — المعركة الميدانية\n\nحين يبأس القرين ينتقل الشيطان إلى أولياء الإنس، فيزينون المعصية ويحاولون دفع الإنسان إلى الغفلة.'},{title:'تكملة الباب الأول',text:'ثالثاً: فخ القداسة — التدليس بالدين\n\nيأتيك الشيطان من مدخل الدين نفسه، فيلبس الباطل ثوب النصيحة ويحاول إدخال فكر يضل عن الله.\n\nالدليل: قال تعالى: {وَإِنَّ الشَّيَاطِينَ لَيُوحُونَ إِلَى أَوْلِيَائِهِمْ لِيُجَادِلُوكُمْ} [سورة الأنعام: 121].\n\nهذه معاينة محدودة من الكتاب؛ بقية المحتوى متاح بعد الشراء.'}],soul:[{title:'معاينة الكتاب الثاني',text:'هذه الصفحة الافتتاحية من الكتاب الثاني. ستُعرض الصفحات الأصلية هنا عند تجهيز نسخة المعاينة.'},{title:'من قلب الفكرة',text:'مساحة من النص تمنح القارئ فكرة واضحة عن أسلوب الكتاب ومضمونه.'},{title:'نهاية المعاينة',text:'أكمل القراءة باقتناء النسخة الكاملة.'}]};
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let modal,id='devil',page=0;
  function build(){
    modal=document.createElement('div');modal.id='newPreviewModal';modal.className='modal';modal.setAttribute('aria-hidden','true');
    modal.innerHTML='<div class="modal-box preview-box new-preview-box"><button class="close" id="newPreviewClose" type="button" aria-label="إغلاق">×</button><p class="eyebrow">معاينة مجانية</p><h2 id="newPreviewTitle"></h2><div class="new-reader"><div class="new-reader-paper"><article id="newPreviewPage"></article><span id="newPreviewFolio">1</span></div><div class="new-reader-controls"><button id="newPrev" type="button">السابق</button><span id="newCounter"></span><button id="newNext" type="button">التالي</button></div></div><div class="new-preview-lock"><h3>أعجبتك البداية؟</h3><p>هذه معاينة مجانية محدودة. أكمل للحصول على النسخة الكاملة.</p><button class="btn dark full" id="newPreviewBuy" type="button">أريد النسخة الكاملة</button></div></div>';
    document.body.appendChild(modal);
    const closeBtn=modal.querySelector('#newPreviewClose'),prev=modal.querySelector('#newPrev'),next=modal.querySelector('#newNext'),buy=modal.querySelector('#newPreviewBuy');
    closeBtn.addEventListener('click',close);prev.addEventListener('click',()=>{if(page>0){page--;render()}});next.addEventListener('click',()=>{if(page<(pages[id]||[]).length-1){page++;render()}});buy.addEventListener('click',()=>{close();document.querySelector('.book-card[data-id="'+id+'"] .buy-btn')?.click()});modal.addEventListener('click',e=>{if(e.target===modal)close()});
    const style=document.createElement('style');style.textContent='.new-preview-box{max-width:900px}.new-reader-paper{position:relative;min-height:430px;background:#f7f0e3;color:#241f19;border-radius:8px;box-shadow:0 18px 45px rgba(0,0,0,.18);padding:46px 55px;overflow:hidden}.new-reader-paper article{font-family:serif;text-align:right;line-height:2;font-size:18px}.new-reader-paper h3{font-size:28px;margin:0 0 20px}.new-reader-paper p{margin:0 0 14px}.new-reader-paper #newPreviewFolio{position:absolute;bottom:15px;left:50%;font-size:12px}.new-reader-controls{display:flex;justify-content:center;align-items:center;gap:22px;margin-top:14px}.new-reader-controls button{width:80px;height:44px;border-radius:22px;border:1px solid currentColor;background:transparent;cursor:pointer}.new-reader-controls button:disabled{opacity:.3}.new-preview-lock{text-align:center;margin-top:18px;padding-top:16px;border-top:1px solid rgba(0,0,0,.1)}@media(max-width:600px){.new-reader-paper{min-height:420px;padding:30px 25px}.new-reader-paper article{font-size:16px}.new-reader-paper h3{font-size:23px}}';document.head.appendChild(style);
  }
  function render(){const list=pages[id]||pages.devil,p=list[page];modal.querySelector('#newPreviewTitle').textContent=id==='devil'?'معركة الشيطان وجنوده مع الإنسان':'معركة السيادة بين فطرة الروح والجسد';modal.querySelector('#newPreviewPage').innerHTML='<span>معاينة · صفحة '+(page+1)+'</span><h3>'+esc(p.title)+'</h3>'+p.text.split('\n\n').map(x=>'<p>'+esc(x)+'</p>').join('')+'<small>نسخة معاينة — جميع الحقوق محفوظة</small>';modal.querySelector('#newPreviewFolio').textContent=page+1;modal.querySelector('#newCounter').textContent='صفحة '+(page+1)+' من '+list.length;modal.querySelector('#newPrev').disabled=page===0;modal.querySelector('#newNext').disabled=page===list.length-1}
  function close(){if(modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}}
  function show(book){id=book||'devil';page=0;if(!modal)build();render();modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
  function bind(){document.querySelectorAll('.book-card .preview-btn').forEach(btn=>{if(btn.dataset.previewBound==='1')return;btn.dataset.previewBound='1';btn.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();show(btn.closest('.book-card')?.dataset.id||'devil')},true)})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();window.addEventListener('load',bind);
})();